require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - "db/schema.rb"
    - "bin/*"
    - "node_modules/**/*"
    - "vendor/**/*"

Layout/IndentationConsistency:
  EnforcedStyle: normal

Layout/IndentationWidth:
  Width: 2

Rails:
  Enabled: true
